apiVersion: v1
kind: ConfigMap
metadata:
  name: player-posix-demo-pod
data:
  PLAYER_LIVES: "5"
  PROPERTIES_FILE_NAME: "user-interface.properties"
  BASE_PROPERTIES: "Template"
  USER_INTERFACE_PROPERTIES: "Dark"